services:

  api-gateway:
    build: ../../apigateway
    container_name: api-gateway
    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: docker

    depends_on:
      - product-service
      - user-service

    networks:
      - ecommerce-network


  product-service:
    build: ../../product-service
    container_name: product-service

    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://host.docker.internal:8761/eureka/

    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      product-db:
        condition: service_healthy

    networks:
      - ecommerce-network


  user-service:
    build: ../../user-service
    container_name: user-service

    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db

    depends_on:
      user-db:
        condition: service_healthy

    networks:
      - ecommerce-network


  product-db:
    image: postgres:17
    container_name: product-db

    ports:
      - "5434:5432"

    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

    volumes:
      - product-db-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d product_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - ecommerce-network


  user-db:
    image: postgres:17
    container_name: user-db

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

    volumes:
      - user-db-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d user_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - ecommerce-network


  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.20.0
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4319:4317"   # OTLP gRpC receiver
      - "4320:4318"    # OTLP HTTP receiver
    networks:
      - ecommerce-network

  otel-collector:
    image: otel/opentelemetry-collector:0.160.0
    container_name: otel-collector
    command: [ "--config=/etc/otelcol/config.yaml" ]
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
    networks:
      - ecommerce-network


volumes:
  product-db-data:
  user-db-data:


networks:
  ecommerce-network:
    driver: bridge