server:
  port: 8081

spring:
  application:
    name: user-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.meneakevit.store/realms/ecommerce
  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info


