package com.ecommerce.order_service.domain;

public enum SagaStep {
    ORDER_CREATED,
    INVENTORY_RESERVATION_PENDING,
    INVENTORY_RESERVED,
    PAYMENT_PENDING,
    PAYMENT_COMPLETED,
    INVENTORY_CONFIRMATION_PENDING,
    INVENTORY_CONFIRMED,
    COMPLETED,
    COMPENSATION_PENDING,
    INVENTORY_RELEASED,
    FAILED
}